import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/app/context/client-provider"
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import { LoginDialog } from "@/src/components/Dialogs/LoginDialog";
import { RegistrationDialog } from "@/src/components/Dialogs/RegistrationDialog";
import { LogOutButton } from "@/src/components/Buttons/LogOutButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider session={session}>
        <div>
          {
            session?.user?.email ? <><LogOutButton /> Logged in as: { session?.user?.email }</> : <><LoginDialog />
            <RegistrationDialog /></>
          }
        </div>
        {children}
        </Provider>
        </body>
    </html>
  );
}
